# Generated by Django 5.0.1 on 2026-02-03 11:34

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier source')),
                ('file_type', models.CharField(help_text='Ex: application/pdf, text/plain', max_length=50, verbose_name='Type MIME')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille du fichier (bytes)')),
                ('file_hash', models.CharField(help_text='Évite les doublons', max_length=64, unique=True, verbose_name='Hash SHA256 du fichier')),
                ('processing_status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='Statut du traitement')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('total_pages', models.IntegerField(default=0, verbose_name='Nombre de pages')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='Nombre de chunks générés')),
                ('total_characters', models.IntegerField(default=0, verbose_name='Nombre total de caractères')),
                ('extracted_metadata', models.JSONField(blank=True, default=dict, help_text='Auteur, date de création, etc.', verbose_name='Métadonnées extraites du PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de traitement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Document source',
                'verbose_name_plural': 'Documents sources',
                'db_table': 'source_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Question posée')),
                ('retrieved_chunks_count', models.IntegerField(default=0, verbose_name='Nombre de chunks récupérés')),
                ('response_text', models.TextField(blank=True, verbose_name='Réponse générée')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Temps de réponse (ms)')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens consommés (LLM)')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Note utilisateur (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la requête')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('source_documents', models.ManyToManyField(blank=True, related_name='queries', to='documents.sourcedocument', verbose_name='Documents consultés')),
            ],
            options={
                'verbose_name': 'Log de requête',
                'verbose_name_plural': 'Logs de requêtes',
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du chunk')),
                ('content_length', models.IntegerField(verbose_name='Longueur du contenu (caractères)')),
                ('embedding', pgvector.django.VectorField(dimensions=768, verbose_name="Vecteur d'embedding")),
                ('chunk_index', models.IntegerField(help_text='Position dans la séquence (0, 1, 2...)', verbose_name='Index du chunk')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Numéro de page source')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Section, paragraphe, etc.', verbose_name='Métadonnées du chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.sourcedocument', verbose_name='Document source')),
            ],
            options={
                'verbose_name': 'Chunk de document',
                'verbose_name_plural': 'Chunks de documents',
                'db_table': 'document_chunks',
                'ordering': ['source_document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['user', '-created_at'], name='source_docu_user_id_3715c0_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['processing_status'], name='source_docu_process_5c8178_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['file_hash'], name='source_docu_file_ha_025a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', '-created_at'], name='query_logs_user_id_0e7784_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['source_document', 'chunk_index'], name='document_ch_source__e1ca7c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='document_ch_page_nu_91bcc3_idx'),
        ),
    ]
